### PR TITLE
ft about section responsive on small, medium and large screens

### PR DESCRIPTION
**Pull request by Chartine02**
Implementation of the about section that is responsive on small, medium and large screens

### CODE REVIEW

**Comment by Ntwalii** [comment]
Please pull dev to get the recent changes i.e background-color...

**Comment by Ntwalii** [comment]
Please pull the dev branch for the previous changes i.e: Background color...

**Review by Ntwalii — APPROVED** [review]
Looks good.

**Review by beylar — APPROVED** [review]
The changes were properly implemented

**Pull request merged**
