### PR TITLE
navbar on desktop

### PR DESCRIPTION
**Pull request by gloriaumutoni**
reduce the top padding
header/navbar should be fixed not sticky!!
Reduce the spacing between links

### CODE REVIEW

**Review by Chartine02 — APPROVED** [review]

**Review by beylar — COMMENTED** [review]
The menu on the navbar is not aligned with the logo on mobile

**Review by beylar — APPROVED** [review]
Looks good.

**Review by josueahadi — APPROVED** [review]
It looks great!

**Review by Kingcedru — CHANGES_REQUESTED** [review]
Remove Javascript DOM

**Review by Kingcedru — APPROVED** [review]
done

**Pull request merged**
