### PR TITLE
Ft/nav bar

### PR DESCRIPTION
**Pull request by gloriaumutoni**
worked on the responsiveness of the navbar

### CODE REVIEW

**Review by Chartine02 — APPROVED** [review]
Great work with the navbar's responsiveness

**Review by Ntwalii — APPROVED** [review]
Work on the changes @josueahadi is about to request and the navbar will be perfect. Great work

**Review by josueahadi — CHANGES_REQUESTED** [review]
This is from your implementation...
image
...and this is what the figma looks like...
image

In our implementation, the yellow shape becomes sticky when the top = 0 (for mobile, tablet, and desktop). And that is correct (well done :)) It seems the navbar on mobile has a slightly larger padding on top to take into consideration that phones have a bezel. So, if you try that, it will somewhat look like the Figma design.

**Review by josueahadi — APPROVED** [review]
It looks much better @beylar :)

**Review by NoellaPromise — APPROVED** [review]

**Pull request merged**
