### PR TITLE
ft/hero section

### PR DESCRIPTION
**Pull request by josueahadi**
So far, @gloriaumutoni and I have worked on the design of the hero section focusing on desktop view. We have added the shapes and positioned them on the screen, and the welcome text is displayed on top of them. We haven't yet added the scroll functionalities where the shapes stick on top of the hero section "on scroll".

### CODE REVIEW

**Comment by josueahadi** [comment]
@gloriaumutoni, I have resolved the conflict we had in the tailwind config file

**Comment by aimee-annabelle** [comment]
The hero section looks amazing. Great work @josueahadi @Ntwalii

**Review by aimee-annabelle — CHANGES_REQUESTED** [review]
remove the extra/unused comments in the hero file

**Review by josueahadi — COMMENTED** [review]
The unused code in the comments have been removed @aimee-annabelle

**Review by aimee-annabelle — APPROVED** [review]

**Review by gloriaumutoni — APPROVED** [review]
great job

**Review by Kingcedru — APPROVED** [review]
approved

**Review by Kingcedru — COMMENTED** [review]
Very good

**Pull request merged**
