### PR TITLE
NavBar

### PR DESCRIPTION
**Pull request by beylar**
Created a nav bar for the large and xl view

### CODE REVIEW

**Comment by aimee-annabelle** [comment]
@beylar, great work. The navigation looks good. 
I would like to point out a few changes to the font size of the text in the middle; it should be 48px, not 46px. and the navigation links on the right also have a font size of 24px. Please look into the corresponding tailwind font size class.
Otherwise, everything looks good well done.

**Comment by josueahadi** [comment]
@beylar @Ntwalii everything looks good. This is ready to merge.

**Comment by aimee-annabelle** [comment]
Make the navbar sticky and position on top of everything when scrolled

**Review by josueahadi — APPROVED** [review]
I have reviewed your recent changes, and they all look as expected. Merge when you are ready!

**Review by aimee-annabelle — APPROVED** [review]

**Review by Chartine02 — APPROVED** [review]

**Pull request merged**
